base_url = "https://clip-template.vercel.app"
[book]
title = "Shihao's Clip"
description = "CLip Clip"
src = "content"
language = "zh"
authors = ["Alex"]

[output.html]
git-repository-url = "https://github.com/theowenyoung/clip-template"
edit-url-template = "https://github.com/theowenyoung/clip-template/edit/main/{path}"
additional-css = ["content/theme/sidebar.css"]
additional-js = ["content/theme/sidebar.js"]

[output.html.search]
enable = false
